---
version: '2'
services:
  drupal:
    image: drupal
    depends_on:
      - postgres
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always
  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: blahdblah
    restart: always
volumes:
  pg_data:
    driver: local
  drupal_modules:
    driver: local
  drupal_profiles:
    driver: local
  drupal_themes:
    driver: local
  drupal_sites:
    driver: local